### ISSUE TITLE
HD FV215b barrel length

### ISSUE THREAD

**Issue by renaissance-design** [Milkym4n/milkysmods#2]
With the v2 update to the FV the barrel has got roughly 5 calibers shorter. Might be an issue when trying to fire past it in a brawl.

**Comment by Milkym4n** [comment]
I'll see what I can do. Stretching the entire barrel on the Z-axis can cause some texture misalignments.

**Comment by renaissance-design** [comment]
Roger that, cheers. Oh, just FYI: I've removed your mods from the woepack installer because they were clashing with your installer - instead I'm [linking to this repo](http://renaissance-design.github.io/woepack/) below the comparison slider so folks can grab all your mods in one bundle. I can put a link directly to your zip in the sidebar if you'd like?

**Comment by Milkym4n** [comment]
Oh that's nice.

Your choice if you want to put a direct link to the zip. Don't mind whatever you do ;)

**Comment by Milkym4n** [comment]
Resizing the barrel isn't feasible the way it's made. Stretched textures along stretched camo pattern make it look ugly.

It shouldn't interfere too much since the crash model hasn't been modified.
